--- # webserver
server:
  port: 8080
  context-path: /
  session:
    timeout: 1800

--- # logging
logging:
  level:
    root: INFO
    com: 
      digitalchina: DEBUG
      
    org.springframework.web.servlet.mvc: debug
    org.mybatis: debug

--- # datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hawkeye?useSSL=false
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 1
    maximum-pool-size: 10
    connection-timeout: 5000

--- # template
spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5

--- # mybatis
mybatis:
  config-location: classpath:mybatis-config.xml #增加mybatis xml风格的支持
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: tk.mybatis.springboot.model

--- # mapper
mapper:
    mappers:
        - tk.mybatis.springboot.util.MyMapper
    not-empty: false
    identity: MYSQL

